image: node:8.11.3

pipelines:
  default:
    - step:
        name: Test build
        deployment: test
        caches:
          - node
        script:
          - npm install
          - npm run build

  branches:
    staging:
    - step:
        name: Tests one more time before deploy
        caches:
        - node
        script:
        - npm install
        - npm run build
    master:
      - step:
          name: Tests one more time before publish to PRODUCTION
          caches:
            - node
          script:
            - npm install
            - npm run build
      - step:
          name: Deploy to PRODUCTION
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git -f HEAD:master
