image: node:8.11.3

pipelines:
  default:
    - step:
        name: Test
        deployment: test
        caches:
          - node
        script:
          - npm install
          - npm run build

  branches:
    staging:
      - step:
          name: Tests before deployment to STAGING
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts: # defining the artifacts to be passed to each future step.
            - build/**
      - step:
          name: Deploy to STAGING
          caches:
            - node
          deployment: staging
          script:
            - cd heroku
            - rm -rf ./build
            - rm -rf .git
            - cp -r ../build ./build
            - git init
            - git add .
            - git config user.email "razvanlomov@gmail.com"
            - git config user.name "bitbucket-pipelines"
            - git commit -m 'dynamic version'
            - git status
            - git remote add origin https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
            - git push origin master --force
    master:
      - step:
          name: Tests one more time before publish to PRODUCTION
          caches:
            - node
          script:
            - npm install
            - npm run build
