# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.11.3

pipelines:
  default:
    - step:
        name: Test build
        caches:
          - node
        script:
          - yarn install
          - yarn build

  branches:
    master:
      - step:
          name: Tests one more time before deploy
          caches:
            - node
          script:
            - yarn install
            - yarn build
      - step:
          name: Deploy to altiore-staging
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
