image: node:8.11.3

pipelines:
  default:
    - step:
        name: Test build
        caches:
          - node
        script:
          - npm install
          - npm run build

  branches:
    master:
      - step:
          name: Tests one more time before deploy
          caches:
            - node
          script:
            - npm install
            - npm run build
      - step:
          name: Deploy to altiore-staging
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
